[project]
name = "dsa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = ["pydantic>=2.11.7", "pytest>=8.4.2"]

[tool.pytest.ini_options]
pythonpath = ["src"]
